[package]
name = "gameclient"
version = "0.1.0"
authors = ["theZiggurat <frappyd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.4"
bevy_rapier3d = "0.8.0"
rapier3d="*"
rand = "0.8.3"
na = "*"
