[package]
name = "gameclient"
version = "0.1.0"
authors = ["theZiggurat <frappyd@gmail.com>"]
edition = "2018"

[dependencies]
bevy= "0.4.0"
bevy_rapier3d = "0.8.0"
rapier3d="*"
rand = "0.8.3"
na = "*"
bevy_egui = "0.1"
bevy_mod_picking = "0.3.7"
